//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/brg/dev/ros-message-parser-cli/RobSharper.Ros.MessageBase/RosType.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Joanneum.Robotics.Ros.MessageBase.RosTypeParser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRosTypeListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class RosTypeBaseListener : IRosTypeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosTypeParser.type_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_input([NotNull] RosTypeParser.Type_inputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosTypeParser.type_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_input([NotNull] RosTypeParser.Type_inputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosTypeParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] RosTypeParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosTypeParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] RosTypeParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosTypeParser.built_in_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuilt_in_type([NotNull] RosTypeParser.Built_in_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosTypeParser.built_in_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuilt_in_type([NotNull] RosTypeParser.Built_in_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosTypeParser.ros_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRos_type([NotNull] RosTypeParser.Ros_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosTypeParser.ros_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRos_type([NotNull] RosTypeParser.Ros_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosTypeParser.ros_package_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRos_package_type([NotNull] RosTypeParser.Ros_package_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosTypeParser.ros_package_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRos_package_type([NotNull] RosTypeParser.Ros_package_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosTypeParser.array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_type([NotNull] RosTypeParser.Array_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosTypeParser.array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_type([NotNull] RosTypeParser.Array_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosTypeParser.variable_array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_array_type([NotNull] RosTypeParser.Variable_array_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosTypeParser.variable_array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_array_type([NotNull] RosTypeParser.Variable_array_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RosTypeParser.fixed_array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixed_array_type([NotNull] RosTypeParser.Fixed_array_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RosTypeParser.fixed_array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixed_array_type([NotNull] RosTypeParser.Fixed_array_typeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace RobSharper.Ros.MessageBase.RosTypeParser
