//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/brg/dev/ros-message-parser-cli/RobSharper.Ros.MessageBase/RosType.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Joanneum.Robotics.Ros.MessageBase.RosTypeParser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class RosTypeLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BOOL=1, INT8=2, UINT8=3, BYTE=4, CHAR=5, INT16=6, UINT16=7, INT32=8, UINT32=9, 
		INT64=10, UINT64=11, FLOAT32=12, FLOAT64=13, STRING=14, TIME=15, DURATION=16, 
		SLASH=17, OPEN_BRACKET=18, CLOSE_BRACKET=19, INTEGER_LITERAL=20, IDENTIFIER=21;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"BOOL", "INT8", "UINT8", "BYTE", "CHAR", "INT16", "UINT16", "INT32", "UINT32", 
		"INT64", "UINT64", "FLOAT32", "FLOAT64", "STRING", "TIME", "DURATION", 
		"SLASH", "OPEN_BRACKET", "CLOSE_BRACKET", "INTEGER_LITERAL", "IDENTIFIER", 
		"OpenBracket", "CloseBracket", "Lowercase", "Uppercase", "Digit"
	};


	public RosTypeLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public RosTypeLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'bool'", "'int8'", "'uint8'", "'byte'", "'char'", "'int16'", "'uint16'", 
		"'int32'", "'uint32'", "'int64'", "'uint64'", "'float32'", "'float64'", 
		"'string'", "'time'", "'duration'", "'/'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BOOL", "INT8", "UINT8", "BYTE", "CHAR", "INT16", "UINT16", "INT32", 
		"UINT32", "INT64", "UINT64", "FLOAT32", "FLOAT64", "STRING", "TIME", "DURATION", 
		"SLASH", "OPEN_BRACKET", "CLOSE_BRACKET", "INTEGER_LITERAL", "IDENTIFIER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "RosType.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static RosTypeLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x17', '\xBF', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x15', '\x6', '\x15', '\xA5', '\n', '\x15', '\r', '\x15', '\xE', 
		'\x15', '\xA6', '\x3', '\x16', '\x3', '\x16', '\x5', '\x16', '\xAB', '\n', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\a', 
		'\x16', '\xB1', '\n', '\x16', '\f', '\x16', '\xE', '\x16', '\xB4', '\v', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', 
		'\x1B', '\x2', '\x2', '\x1C', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', 
		')', '\x16', '+', '\x17', '-', '\x2', '/', '\x2', '\x31', '\x2', '\x33', 
		'\x2', '\x35', '\x2', '\x3', '\x2', '\x5', '\x3', '\x2', '\x32', ';', 
		'\x3', '\x2', '\x63', '|', '\x3', '\x2', '\x43', '\\', '\x2', '\xBF', 
		'\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x37', '\x3', '\x2', '\x2', '\x2', '\x5', '<', '\x3', '\x2', '\x2', 
		'\x2', '\a', '\x41', '\x3', '\x2', '\x2', '\x2', '\t', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\v', 'L', '\x3', '\x2', '\x2', '\x2', '\r', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\xF', 'W', '\x3', '\x2', '\x2', '\x2', '\x11', '^', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\x15', 'k', '\x3', '\x2', '\x2', '\x2', '\x17', 'q', '\x3', '\x2', '\x2', 
		'\x2', '\x19', 'x', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\x88', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '!', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '#', '\x9D', '\x3', '\x2', '\x2', '\x2', '%', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\'', '\xA1', '\x3', '\x2', '\x2', '\x2', ')', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '+', '\xAA', '\x3', '\x2', '\x2', '\x2', '-', '\xB5', 
		'\x3', '\x2', '\x2', '\x2', '/', '\xB7', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xB9', '\x3', '\x2', '\x2', '\x2', '\x33', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xBD', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\a', 
		'\x64', '\x2', '\x2', '\x38', '\x39', '\a', 'q', '\x2', '\x2', '\x39', 
		':', '\a', 'q', '\x2', '\x2', ':', ';', '\a', 'n', '\x2', '\x2', ';', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '<', '=', '\a', 'k', '\x2', '\x2', 
		'=', '>', '\a', 'p', '\x2', '\x2', '>', '?', '\a', 'v', '\x2', '\x2', 
		'?', '@', '\a', ':', '\x2', '\x2', '@', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x41', '\x42', '\a', 'w', '\x2', '\x2', '\x42', '\x43', '\a', 'k', '\x2', 
		'\x2', '\x43', '\x44', '\a', 'p', '\x2', '\x2', '\x44', '\x45', '\a', 
		'v', '\x2', '\x2', '\x45', '\x46', '\a', ':', '\x2', '\x2', '\x46', '\b', 
		'\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '\x64', '\x2', '\x2', 'H', 
		'I', '\a', '{', '\x2', '\x2', 'I', 'J', '\a', 'v', '\x2', '\x2', 'J', 
		'K', '\a', 'g', '\x2', '\x2', 'K', '\n', '\x3', '\x2', '\x2', '\x2', 'L', 
		'M', '\a', '\x65', '\x2', '\x2', 'M', 'N', '\a', 'j', '\x2', '\x2', 'N', 
		'O', '\a', '\x63', '\x2', '\x2', 'O', 'P', '\a', 't', '\x2', '\x2', 'P', 
		'\f', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\a', 'k', '\x2', '\x2', 'R', 
		'S', '\a', 'p', '\x2', '\x2', 'S', 'T', '\a', 'v', '\x2', '\x2', 'T', 
		'U', '\a', '\x33', '\x2', '\x2', 'U', 'V', '\a', '\x38', '\x2', '\x2', 
		'V', '\xE', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', 'w', '\x2', '\x2', 
		'X', 'Y', '\a', 'k', '\x2', '\x2', 'Y', 'Z', '\a', 'p', '\x2', '\x2', 
		'Z', '[', '\a', 'v', '\x2', '\x2', '[', '\\', '\a', '\x33', '\x2', '\x2', 
		'\\', ']', '\a', '\x38', '\x2', '\x2', ']', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '^', '_', '\a', 'k', '\x2', '\x2', '_', '`', '\a', 'p', '\x2', 
		'\x2', '`', '\x61', '\a', 'v', '\x2', '\x2', '\x61', '\x62', '\a', '\x35', 
		'\x2', '\x2', '\x62', '\x63', '\a', '\x34', '\x2', '\x2', '\x63', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', 'w', '\x2', '\x2', '\x65', 
		'\x66', '\a', 'k', '\x2', '\x2', '\x66', 'g', '\a', 'p', '\x2', '\x2', 
		'g', 'h', '\a', 'v', '\x2', '\x2', 'h', 'i', '\a', '\x35', '\x2', '\x2', 
		'i', 'j', '\a', '\x34', '\x2', '\x2', 'j', '\x14', '\x3', '\x2', '\x2', 
		'\x2', 'k', 'l', '\a', 'k', '\x2', '\x2', 'l', 'm', '\a', 'p', '\x2', 
		'\x2', 'm', 'n', '\a', 'v', '\x2', '\x2', 'n', 'o', '\a', '\x38', '\x2', 
		'\x2', 'o', 'p', '\a', '\x36', '\x2', '\x2', 'p', '\x16', '\x3', '\x2', 
		'\x2', '\x2', 'q', 'r', '\a', 'w', '\x2', '\x2', 'r', 's', '\a', 'k', 
		'\x2', '\x2', 's', 't', '\a', 'p', '\x2', '\x2', 't', 'u', '\a', 'v', 
		'\x2', '\x2', 'u', 'v', '\a', '\x38', '\x2', '\x2', 'v', 'w', '\a', '\x36', 
		'\x2', '\x2', 'w', '\x18', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\a', 
		'h', '\x2', '\x2', 'y', 'z', '\a', 'n', '\x2', '\x2', 'z', '{', '\a', 
		'q', '\x2', '\x2', '{', '|', '\a', '\x63', '\x2', '\x2', '|', '}', '\a', 
		'v', '\x2', '\x2', '}', '~', '\a', '\x35', '\x2', '\x2', '~', '\x7F', 
		'\a', '\x34', '\x2', '\x2', '\x7F', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		'\x80', '\x81', '\a', 'h', '\x2', '\x2', '\x81', '\x82', '\a', 'n', '\x2', 
		'\x2', '\x82', '\x83', '\a', 'q', '\x2', '\x2', '\x83', '\x84', '\a', 
		'\x63', '\x2', '\x2', '\x84', '\x85', '\a', 'v', '\x2', '\x2', '\x85', 
		'\x86', '\a', '\x38', '\x2', '\x2', '\x86', '\x87', '\a', '\x36', '\x2', 
		'\x2', '\x87', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', 
		'u', '\x2', '\x2', '\x89', '\x8A', '\a', 'v', '\x2', '\x2', '\x8A', '\x8B', 
		'\a', 't', '\x2', '\x2', '\x8B', '\x8C', '\a', 'k', '\x2', '\x2', '\x8C', 
		'\x8D', '\a', 'p', '\x2', '\x2', '\x8D', '\x8E', '\a', 'i', '\x2', '\x2', 
		'\x8E', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\a', 'v', 
		'\x2', '\x2', '\x90', '\x91', '\a', 'k', '\x2', '\x2', '\x91', '\x92', 
		'\a', 'o', '\x2', '\x2', '\x92', '\x93', '\a', 'g', '\x2', '\x2', '\x93', 
		' ', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\a', '\x66', '\x2', 
		'\x2', '\x95', '\x96', '\a', 'w', '\x2', '\x2', '\x96', '\x97', '\a', 
		't', '\x2', '\x2', '\x97', '\x98', '\a', '\x63', '\x2', '\x2', '\x98', 
		'\x99', '\a', 'v', '\x2', '\x2', '\x99', '\x9A', '\a', 'k', '\x2', '\x2', 
		'\x9A', '\x9B', '\a', 'q', '\x2', '\x2', '\x9B', '\x9C', '\a', 'p', '\x2', 
		'\x2', '\x9C', '\"', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\a', 
		'\x31', '\x2', '\x2', '\x9E', '$', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\xA0', '\x5', '-', '\x17', '\x2', '\xA0', '&', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\xA2', '\x5', '/', '\x18', '\x2', '\xA2', '(', '\x3', '\x2', 
		'\x2', '\x2', '\xA3', '\xA5', '\t', '\x2', '\x2', '\x2', '\xA4', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', 
		'\xA6', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\x3', '\x2', 
		'\x2', '\x2', '\xA7', '*', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xAB', 
		'\x5', '\x31', '\x19', '\x2', '\xA9', '\xAB', '\x5', '\x33', '\x1A', '\x2', 
		'\xAA', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xA9', '\x3', '\x2', 
		'\x2', '\x2', '\xAB', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xB1', 
		'\x5', '\x31', '\x19', '\x2', '\xAD', '\xB1', '\x5', '\x33', '\x1A', '\x2', 
		'\xAE', '\xB1', '\x5', '\x35', '\x1B', '\x2', '\xAF', '\xB1', '\a', '\x61', 
		'\x2', '\x2', '\xB0', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xAD', 
		'\x3', '\x2', '\x2', '\x2', '\xB0', '\xAE', '\x3', '\x2', '\x2', '\x2', 
		'\xB0', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB4', '\x3', '\x2', 
		'\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', 
		'\x3', '\x2', '\x2', '\x2', '\xB3', ',', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\a', ']', '\x2', 
		'\x2', '\xB6', '.', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\a', 
		'_', '\x2', '\x2', '\xB8', '\x30', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBA', '\t', '\x3', '\x2', '\x2', '\xBA', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\xBC', '\t', '\x4', '\x2', '\x2', '\xBC', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xBD', '\xBE', '\t', '\x2', '\x2', '\x2', '\xBE', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\a', '\x2', '\xA6', '\xAA', '\xB0', 
		'\xB2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace RobSharper.Ros.MessageBase.RosTypeParser
